config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'static_notes#about'

  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', note_path %>
<%= link_to 'About', root_path %>
<%= link_to 'Pages', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjNameNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1>Notes</h1>
<% @notes.each do |note| %>
  <h2><%= note.title %></h2>
  <%= link_to 'Show Note', note_path(note) %>
  <%= link_to 'Edit page', edit_note_path(note) %>
<% end %>

app/views/notes/new.html.erb
<h1>New Page</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<h4><%= @note.author %></h1>
<p><%= @note.body %></p>
<%= link_to 'Back', notes_path %>